export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RETRIEVE_ROLES = "RETRIEVE_ROLES";
export const CREATE_ROLE = "CREATE_ROLE";

export const RETRIEVE_AUTHORS = "RETRIEVE_AUTHORS";
export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const RETRIEVE_AUTHOR_SELECT = "RETRIEVE_AUTHOR_SELECT";
export const EDIT_AUTHOR = "EDIT_AUTHOR";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const SEARCH_AUTHOR = "SEARCH_AUTHOR";

export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USER_SELECT = "RETRIEVE_USER_SELECT";
export const EDIT_USER = "EDIT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const SEARCH_USER = "SEARCH_USER";

export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const RETRIEVE_CATEGORY_SELECT = "RETRIEVE_CATEGORY_SELECT";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SEARCH_CATEGORY = "SEARCH_CATEGORY";

export const RETRIEVE_MP3 = "RETRIEVE_MP3";
export const EDIT_MP3 = "EDIT_MP3";
export const UPDATE_MP3 = "UPDATE_MP3";
export const DELETE_MP3 = "DELETE_MP3";
export const SEARCH_MP3 = "SEARCH_MP3";

export const RETRIEVE_MP3USERS = "RETRIEVE_MP3USERS";
export const DELETE_MP3USERS = "DELETE_MP3USERS";
export const STATUS_MP3USERS = "STATUS_MP3USERS";
export const SEARCH_MP3USERS = "SEARCH_MP3USERS";

export const RETRIEVE_HOROSCOPES = "RETRIEVE_HOROSCOPES";
export const CREATE_HOROSCOPE = "CREATE_HOROSCOPE";
export const RETRIEVE_HOROSCOPE_SELECT = "RETRIEVE_HOROSCOPE_SELECT";
export const EDIT_HOROSCOPE = "EDIT_HOROSCOPE";
export const UPDATE_HOROSCOPE = "UPDATE_HOROSCOPE";
export const DELETE_HOROSCOPE = "DELETE_HOROSCOPE";
export const STATUS_HOROSCOPE = "STATUS_HOROSCOPE";
export const SEARCH_HOROSCOPE = "SEARCH_HOROSCOPE";

export const RETRIEVE_HOROSCOPE_LOVES = "RETRIEVE_HOROSCOPE_LOVES";
export const EDIT_HOROSCOPE_LOVES = "EDIT_HOROSCOPE_LOVES";
export const UPDATE_HOROSCOPE_LOVES = "UPDATE_HOROSCOPE_LOVES";
export const SEARCH_HOROSCOPE_LOVE = "SEARCH_HOROSCOPE_LOVE";

export const RETRIEVE_HOROSCOPE_PROPERTIES = "RETRIEVE_HOROSCOPE_PROPERTIES";
export const RETRIEVE_HOROSCOPE_PROPERTY_SELECT = "RETRIEVE_HOROSCOPE_PROPERTY_SELECT";
export const CREATE_HOROSCOPE_PROPERTY = "CREATE_HOROSCOPE_PROPERTY";
export const EDIT_HOROSCOPE_PROPERTY = "EDIT_HOROSCOPE_PROPERTY";
export const UPDATE_HOROSCOPE_PROPERTY = "UPDATE_HOROSCOPE_PROPERTY";
export const DELETE_HOROSCOPE_PROPERTY = "DELETE_HOROSCOPE_PROPERTY";
export const STATUS_HOROSCOPE_PROPERTY = "STATUS_HOROSCOPE_PROPERTY";
export const SEARCH_HOROSCOPE_PROPERTY = "SEARCH_HOROSCOPE_PROPERTY";

export const RETRIEVE_NEWS = "RETRIEVE_NEWS";
export const RETRIEVE_NEWS_SELECT = "RETRIEVE_NEWS_SELECT";
export const SEARCH_NEWS = "SEARCH_NEWS";

export const RETRIEVE_LOGS = "RETRIEVE_LOGS";
export const DELETE_LOG = "DELETE_LOG";
export const SEARCH_LOG = "SEARCH_LOG";

export const RETRIEVE_CONTACTS = "RETRIEVE_CONTACTS";
export const FIND_CONTACT = "FIND_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";

export const RETRIEVE_CATEGORY_LINKS = "RETRIEVE_CATEGORY_LINKS";
export const CREATE_CATEGORY_LINK = "CREATE_CATEGORY_LINK";
export const RETRIEVE_CATEGORY_LINK_SELECT = "RETRIEVE_CATEGORY_LINK_SELECT";
export const EDIT_CATEGORY_LINK = "EDIT_CATEGORY_LINK";
export const UPDATE_CATEGORY_LINK = "UPDATE_CATEGORY_LINK";
export const DELETE_CATEGORY_LINK = "DELETE_CATEGORY_LINK";
export const STATUS_CATEGORY_LINK = "STATUS_CATEGORY_LINK";
export const SEARCH_CATEGORY_LINK = "SEARCH_CATEGORY_LINK";

export const RETRIEVE_SEO_NEWS = "RETRIEVE_SEO_NEWS";
export const EDIT_SEO_NEWS = "EDIT_SEO_NEWS";
export const UPDATE_SEO_NEWS = "UPDATE_SEO_NEWS";
export const SEARCH_SEO_NEWS = "SEARCH_SEO_NEWS";

export const RETRIEVE_SEO_SITEMAP = "RETRIEVE_SEO_SITEMAP";
export const EDIT_SEO_SITEMAP = "EDIT_SEO_SITEMAP";
export const UPDATE_SEO_SITEMAP = "UPDATE_SEO_SITEMAP";
export const SEARCH_SEO_SITEMAP = "SEARCH_SEO_SITEMAP";

export const RETRIEVE_SEO_GOOGLE = "RETRIEVE_SEO_GOOGLE";
export const RETRIEVE_SEO_GOOGLE_INDEX = "RETRIEVE_SEO_GOOGLE_INDEX";
export const RETRIEVE_SEO_GOOGLE_INSERT = "RETRIEVE_SEO_GOOGLE_INSERT";
export const RETRIEVE_SEO_GOOGLE_DELETE = "RETRIEVE_SEO_GOOGLE_DELETE";

export const RETRIEVE_VIDEOS = "RETRIEVE_VIDEOS";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";

export const RETRIEVE_STATISTICS = "RETRIEVE_STATISTICS";
export const RETRIEVE_STATISTIC_TYPE = "RETRIEVE_STATISTIC_TYPE";
export const SEARCH_STATISTICS = "SEARCH_STATISTICS";